title: sns
author: Dataloop.IO
version: 1.0.0
description: Dashboards and alert rules for SNS notifications monitored with the AWS integration
icon:
    name: autoscaling
    background: orange
    foreground: white
