title: Postfix
author: Dataloop.IO
version: 1.0.0
description: Postfix status, mail queue size and cpu / memory stats for core processes
icon:
    name: postfix
    background: gray
    foreground: white
