title: ElasticSearch
author: Dataloop.IO
version: 1.0.0
description: Queries the stats and health endpoints for all Elastic Search metrics
icon:
    name: elasticsearch
    background: light green
    foreground: white