title: Nginx
author: Dataloop.IO
version: 1.0.0
description: Nginx http codes and response times. You will need to follow the instructions in nginx.py for setup.
icon:
    name: nginx
    background: green
    foreground: white
