title: s3
author: Dataloop.IO
version: 1.0.0
description: Dashboards and alert rules for s3 buckets monitored with the AWS integration
icon:
    name: aws
    background: orange
    foreground: white
