title: Google Analytics
author: Dataloop.IO
version: 1.0.0
description: Add metrics from Google Analytics to your dashboards.
instructions_required: true
icon:
    name: website
    background: "#EE5A30"
    foreground: "#F7981E"