title: lambda
author: Dataloop.IO
version: 1.0.0
description: Dashboards and alert rules for lambda monitored with the AWS integration
icon:
    name: aws
    background: orange
    foreground: white
