title: MySQL
author: Dataloop.IO
version: 1.0.0
description: MySQL monitoring. You may need to edit the mysql.py plugin to set username and password.
icon:
    name: mysql
    background: darkblue
    foreground: orange
