title: Postgres
author: Dataloop.IO
version: 1.0.0
description: Postgres availability and performance monitoring. You will need to edit postgres.py to specify settings.
icon:
    name: postgres
    background: white
    foreground: blue
