title: All Systems
criteria:
  - metric: agent.status
    scope:
      tag: all
    condition:
      timeout: 120
      threshold: false
  - metric: base.load_fractional
    scope:
      tag: all
    condition:
      timeout: 120
      threshold: 3
actions:
  - emails: []
    message: ''
